// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/cx/v3/version.proto

package com.google.cloud.dialogflow.cx.v3;

public interface CreateVersionOperationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.dialogflow.cx.v3.CreateVersionOperationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the created version.
   * Format:
   * `projects/&lt;ProjectID&gt;/locations/&lt;LocationID&gt;/agents/&lt;AgentID&gt;/flows/&lt;FlowID&gt;/versions/&lt;VersionID&gt;`.
   * </pre>
   *
   * <code>string version = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Name of the created version.
   * Format:
   * `projects/&lt;ProjectID&gt;/locations/&lt;LocationID&gt;/agents/&lt;AgentID&gt;/flows/&lt;FlowID&gt;/versions/&lt;VersionID&gt;`.
   * </pre>
   *
   * <code>string version = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
