// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/cx/v3/fulfillment.proto

package com.google.cloud.dialogflow.cx.v3;

public interface FulfillmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.dialogflow.cx.v3.Fulfillment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The list of rich message responses to present to the user.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.ResponseMessage messages = 1;</code>
   */
  java.util.List<com.google.cloud.dialogflow.cx.v3.ResponseMessage> 
      getMessagesList();
  /**
   * <pre>
   * The list of rich message responses to present to the user.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.ResponseMessage messages = 1;</code>
   */
  com.google.cloud.dialogflow.cx.v3.ResponseMessage getMessages(int index);
  /**
   * <pre>
   * The list of rich message responses to present to the user.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.ResponseMessage messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <pre>
   * The list of rich message responses to present to the user.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.ResponseMessage messages = 1;</code>
   */
  java.util.List<? extends com.google.cloud.dialogflow.cx.v3.ResponseMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <pre>
   * The list of rich message responses to present to the user.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.ResponseMessage messages = 1;</code>
   */
  com.google.cloud.dialogflow.cx.v3.ResponseMessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * The webhook to call.
   * Format: `projects/&lt;Project ID&gt;/locations/&lt;Location ID&gt;/agents/&lt;Agent
   * ID&gt;/webhooks/&lt;Webhook ID&gt;`.
   * </pre>
   *
   * <code>string webhook = 2 [(.google.api.resource_reference) = { ... }</code>
   * @return The webhook.
   */
  java.lang.String getWebhook();
  /**
   * <pre>
   * The webhook to call.
   * Format: `projects/&lt;Project ID&gt;/locations/&lt;Location ID&gt;/agents/&lt;Agent
   * ID&gt;/webhooks/&lt;Webhook ID&gt;`.
   * </pre>
   *
   * <code>string webhook = 2 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for webhook.
   */
  com.google.protobuf.ByteString
      getWebhookBytes();

  /**
   * <pre>
   * The tag used by the webhook to identify which fulfillment is being called.
   * This field is required if `webhook` is specified.
   * </pre>
   *
   * <code>string tag = 3;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <pre>
   * The tag used by the webhook to identify which fulfillment is being called.
   * This field is required if `webhook` is specified.
   * </pre>
   *
   * <code>string tag = 3;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <pre>
   * Set parameter values before executing the webhook.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction set_parameter_actions = 4;</code>
   */
  java.util.List<com.google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction> 
      getSetParameterActionsList();
  /**
   * <pre>
   * Set parameter values before executing the webhook.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction set_parameter_actions = 4;</code>
   */
  com.google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction getSetParameterActions(int index);
  /**
   * <pre>
   * Set parameter values before executing the webhook.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction set_parameter_actions = 4;</code>
   */
  int getSetParameterActionsCount();
  /**
   * <pre>
   * Set parameter values before executing the webhook.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction set_parameter_actions = 4;</code>
   */
  java.util.List<? extends com.google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterActionOrBuilder> 
      getSetParameterActionsOrBuilderList();
  /**
   * <pre>
   * Set parameter values before executing the webhook.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterAction set_parameter_actions = 4;</code>
   */
  com.google.cloud.dialogflow.cx.v3.Fulfillment.SetParameterActionOrBuilder getSetParameterActionsOrBuilder(
      int index);

  /**
   * <pre>
   * Conditional cases for this fulfillment.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases conditional_cases = 5;</code>
   */
  java.util.List<com.google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases> 
      getConditionalCasesList();
  /**
   * <pre>
   * Conditional cases for this fulfillment.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases conditional_cases = 5;</code>
   */
  com.google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases getConditionalCases(int index);
  /**
   * <pre>
   * Conditional cases for this fulfillment.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases conditional_cases = 5;</code>
   */
  int getConditionalCasesCount();
  /**
   * <pre>
   * Conditional cases for this fulfillment.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases conditional_cases = 5;</code>
   */
  java.util.List<? extends com.google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCasesOrBuilder> 
      getConditionalCasesOrBuilderList();
  /**
   * <pre>
   * Conditional cases for this fulfillment.
   * </pre>
   *
   * <code>repeated .google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCases conditional_cases = 5;</code>
   */
  com.google.cloud.dialogflow.cx.v3.Fulfillment.ConditionalCasesOrBuilder getConditionalCasesOrBuilder(
      int index);
}
