/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/cx/v3beta1/test_case.proto

package com.google.cloud.dialogflow.cx.v3beta1;

public final class TestCaseProto {
  private TestCaseProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCase_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_UserInput_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_UserInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_VirtualAgentOutput_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_VirtualAgentOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestRunDifference_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestRunDifference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_TransitionNode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_TransitionNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_Transition_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_Transition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_Intent_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_Intent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchDeleteTestCasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchDeleteTestCasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_CreateTestCaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_CreateTestCaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_UpdateTestCaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_UpdateTestCaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_GetTestCaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_GetTestCaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestError_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseError_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n2google/cloud/dialogflow/cx/v3beta1/tes"
          + "t_case.proto\022\"google.cloud.dialogflow.cx"
          + ".v3beta1\032\034google/api/annotations.proto\032\027"
          + "google/api/client.proto\032\037google/api/fiel"
          + "d_behavior.proto\032\031google/api/resource.pr"
          + "oto\032-google/cloud/dialogflow/cx/v3beta1/"
          + "flow.proto\032/google/cloud/dialogflow/cx/v"
          + "3beta1/intent.proto\032-google/cloud/dialog"
          + "flow/cx/v3beta1/page.proto\0329google/cloud"
          + "/dialogflow/cx/v3beta1/response_message."
          + "proto\0320google/cloud/dialogflow/cx/v3beta"
          + "1/session.proto\032#google/longrunning/oper"
          + "ations.proto\032\033google/protobuf/empty.prot"
          + "o\032 google/protobuf/field_mask.proto\032\034goo"
          + "gle/protobuf/struct.proto\032\037google/protob"
          + "uf/timestamp.proto\032\027google/rpc/status.pr"
          + "oto\"\356\003\n\010TestCase\022\014\n\004name\030\001 \001(\t\022\014\n\004tags\030\002"
          + " \003(\t\022\031\n\014display_name\030\003 \001(\tB\003\340A\002\022\r\n\005notes"
          + "\030\004 \001(\t\022C\n\013test_config\030\r \001(\0132..google.clo"
          + "ud.dialogflow.cx.v3beta1.TestConfig\022Z\n\034t"
          + "est_case_conversation_turns\030\005 \003(\01324.goog"
          + "le.cloud.dialogflow.cx.v3beta1.Conversat"
          + "ionTurn\0226\n\rcreation_time\030\n \001(\0132\032.google."
          + "protobuf.TimestampB\003\340A\003\022L\n\020last_test_res"
          + "ult\030\014 \001(\01322.google.cloud.dialogflow.cx.v"
          + "3beta1.TestCaseResult:u\352Ar\n\"dialogflow.g"
          + "oogleapis.com/TestCase\022Lprojects/{projec"
          + "t}/locations/{location}/agents/{agent}/t"
          + "estCases/{test_case}\"\270\003\n\016TestCaseResult\022"
          + "\014\n\004name\030\001 \001(\t\022B\n\013environment\030\002 \001(\tB-\340A\001\372"
          + "A\'\n%dialogflow.googleapis.com/Environmen"
          + "t\022P\n\022conversation_turns\030\003 \003(\01324.google.c"
          + "loud.dialogflow.cx.v3beta1.ConversationT"
          + "urn\022C\n\013test_result\030\004 \001(\0162..google.cloud."
          + "dialogflow.cx.v3beta1.TestResult\022-\n\ttest"
          + "_time\030\005 \001(\0132\032.google.protobuf.Timestamp:"
          + "\215\001\352A\211\001\n(dialogflow.googleapis.com/TestCa"
          + "seResult\022]projects/{project}/locations/{"
          + "location}/agents/{agent}/testCases/{test"
          + "_case}/results/{result}\"\\\n\nTestConfig\022\033\n"
          + "\023tracking_parameters\030\001 \003(\t\0221\n\004flow\030\002 \001(\t"
          + "B#\372A \n\036dialogflow.googleapis.com/Flow\"\277\006"
          + "\n\020ConversationTurn\022R\n\nuser_input\030\001 \001(\0132>"
          + ".google.cloud.dialogflow.cx.v3beta1.Conv"
          + "ersationTurn.UserInput\022e\n\024virtual_agent_"
          + "output\030\002 \001(\0132G.google.cloud.dialogflow.c"
          + "x.v3beta1.ConversationTurn.VirtualAgentO"
          + "utput\032\234\001\n\tUserInput\022=\n\005input\030\005 \001(\0132..goo"
          + "gle.cloud.dialogflow.cx.v3beta1.QueryInp"
          + "ut\0224\n\023injected_parameters\030\002 \001(\0132\027.google"
          + ".protobuf.Struct\022\032\n\022is_webhook_enabled\030\003"
          + " \001(\010\032\320\003\n\022VirtualAgentOutput\0223\n\022session_p"
          + "arameters\030\004 \001(\0132\027.google.protobuf.Struct"
          + "\022O\n\013differences\030\005 \003(\01325.google.cloud.dia"
          + "logflow.cx.v3beta1.TestRunDifferenceB\003\340A"
          + "\003\0228\n\017diagnostic_info\030\006 \001(\0132\027.google.prot"
          + "obuf.StructB\006\340A\002\340A\004\022D\n\020triggered_intent\030"
          + "\007 \001(\0132*.google.cloud.dialogflow.cx.v3bet"
          + "a1.Intent\022>\n\014current_page\030\010 \001(\0132(.google"
          + ".cloud.dialogflow.cx.v3beta1.Page\022P\n\016tex"
          + "t_responses\030\t \003(\01328.google.cloud.dialogf"
          + "low.cx.v3beta1.ResponseMessage.Text\022\"\n\006s"
          + "tatus\030\n \001(\0132\022.google.rpc.Status\"\322\001\n\021Test"
          + "RunDifference\022L\n\004type\030\001 \001(\0162>.google.clo"
          + "ud.dialogflow.cx.v3beta1.TestRunDifferen"
          + "ce.DiffType\022\023\n\013description\030\002 \001(\t\"Z\n\010Diff"
          + "Type\022\031\n\025DIFF_TYPE_UNSPECIFIED\020\000\022\n\n\006INTEN"
          + "T\020\001\022\010\n\004PAGE\020\002\022\016\n\nPARAMETERS\020\003\022\r\n\tUTTERAN"
          + "CE\020\004\"\226\005\n\022TransitionCoverage\022V\n\013transitio"
          + "ns\030\001 \003(\0132A.google.cloud.dialogflow.cx.v3"
          + "beta1.TransitionCoverage.Transition\022\026\n\016c"
          + "overage_score\030\002 \001(\002\032\214\001\n\016TransitionNode\0228"
          + "\n\004page\030\001 \001(\0132(.google.cloud.dialogflow.c"
          + "x.v3beta1.PageH\000\0228\n\004flow\030\002 \001(\0132(.google."
          + "cloud.dialogflow.cx.v3beta1.FlowH\000B\006\n\004ki"
          + "nd\032\200\003\n\nTransition\022U\n\006source\030\001 \001(\0132E.goog"
          + "le.cloud.dialogflow.cx.v3beta1.Transitio"
          + "nCoverage.TransitionNode\022\r\n\005index\030\004 \001(\005\022"
          + "U\n\006target\030\002 \001(\0132E.google.cloud.dialogflo"
          + "w.cx.v3beta1.TransitionCoverage.Transiti"
          + "onNode\022\017\n\007covered\030\003 \001(\010\022O\n\020transition_ro"
          + "ute\030\005 \001(\01323.google.cloud.dialogflow.cx.v"
          + "3beta1.TransitionRouteH\000\022I\n\revent_handle"
          + "r\030\006 \001(\01320.google.cloud.dialogflow.cx.v3b"
          + "eta1.EventHandlerH\000B\010\n\006detail\"\306\001\n\016Intent"
          + "Coverage\022J\n\007intents\030\001 \003(\01329.google.cloud"
          + ".dialogflow.cx.v3beta1.IntentCoverage.In"
          + "tent\022\026\n\016coverage_score\030\002 \001(\002\032P\n\006Intent\0225"
          + "\n\006intent\030\001 \001(\tB%\372A\"\n dialogflow.googleap"
          + "is.com/Intent\022\017\n\007covered\030\002 \001(\010\"\200\002\n\030Calcu"
          + "lateCoverageRequest\0226\n\005agent\030\003 \001(\tB\'\340A\002\372"
          + "A!\n\037dialogflow.googleapis.com/Agent\022\\\n\004t"
          + "ype\030\002 \001(\0162I.google.cloud.dialogflow.cx.v"
          + "3beta1.CalculateCoverageRequest.Coverage"
          + "TypeB\003\340A\002\"N\n\014CoverageType\022\035\n\031COVERAGE_TY"
          + "PE_UNSPECIFIED\020\000\022\n\n\006INTENT\020\001\022\023\n\017PAGE_TRA"
          + "NSITION\020\002\"\207\002\n\031CalculateCoverageResponse\022"
          + "3\n\005agent\030\005 \001(\tB$\372A!\n\037dialogflow.googleap"
          + "is.com/Agent\022M\n\017intent_coverage\030\002 \001(\01322."
          + "google.cloud.dialogflow.cx.v3beta1.Inten"
          + "tCoverageH\000\022U\n\023transition_coverage\030\004 \001(\013"
          + "26.google.cloud.dialogflow.cx.v3beta1.Tr"
          + "ansitionCoverageH\000B\017\n\rcoverage_type\"\223\002\n\024"
          + "ListTestCasesRequest\022:\n\006parent\030\001 \001(\tB*\340A"
          + "\002\372A$\022\"dialogflow.googleapis.com/TestCase"
          + "\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\022"
          + "S\n\004view\030\004 \001(\0162E.google.cloud.dialogflow."
          + "cx.v3beta1.ListTestCasesRequest.TestCase"
          + "View\"C\n\014TestCaseView\022\036\n\032TEST_CASE_VIEW_U"
          + "NSPECIFIED\020\000\022\t\n\005BASIC\020\001\022\010\n\004FULL\020\002\"r\n\025Lis"
          + "tTestCasesResponse\022@\n\ntest_cases\030\001 \003(\0132,"
          + ".google.cloud.dialogflow.cx.v3beta1.Test"
          + "Case\022\027\n\017next_page_token\030\002 \001(\t\"\224\001\n\033BatchD"
          + "eleteTestCasesRequest\022:\n\006parent\030\001 \001(\tB*\340"
          + "A\002\372A$\022\"dialogflow.googleapis.com/TestCas"
          + "e\0229\n\005names\030\003 \003(\tB*\340A\002\372A$\n\"dialogflow.goo"
          + "gleapis.com/TestCase\"\231\001\n\025CreateTestCaseR"
          + "equest\022:\n\006parent\030\001 \001(\tB*\340A\002\372A$\022\"dialogfl"
          + "ow.googleapis.com/TestCase\022D\n\ttest_case\030"
          + "\002 \001(\0132,.google.cloud.dialogflow.cx.v3bet"
          + "a1.TestCaseB\003\340A\002\"\223\001\n\025UpdateTestCaseReque"
          + "st\022D\n\ttest_case\030\001 \001(\0132,.google.cloud.dia"
          + "logflow.cx.v3beta1.TestCaseB\003\340A\002\0224\n\013upda"
          + "te_mask\030\002 \001(\0132\032.google.protobuf.FieldMas"
          + "kB\003\340A\002\"N\n\022GetTestCaseRequest\0228\n\004name\030\001 \001"
          + "(\tB*\340A\002\372A$\n\"dialogflow.googleapis.com/Te"
          + "stCase\"\222\001\n\022RunTestCaseRequest\0228\n\004name\030\001 "
          + "\001(\tB*\340A\002\372A$\n\"dialogflow.googleapis.com/T"
          + "estCase\022B\n\013environment\030\002 \001(\tB-\340A\001\372A\'\n%di"
          + "alogflow.googleapis.com/Environment\"Y\n\023R"
          + "unTestCaseResponse\022B\n\006result\030\002 \001(\01322.goo"
          + "gle.cloud.dialogflow.cx.v3beta1.TestCase"
          + "Result\"\025\n\023RunTestCaseMetadata\"\332\001\n\030BatchR"
          + "unTestCasesRequest\022:\n\006parent\030\001 \001(\tB*\340A\002\372"
          + "A$\022\"dialogflow.googleapis.com/TestCase\022B"
          + "\n\013environment\030\002 \001(\tB-\340A\001\372A\'\n%dialogflow."
          + "googleapis.com/Environment\022>\n\ntest_cases"
          + "\030\003 \003(\tB*\340A\002\372A$\n\"dialogflow.googleapis.co"
          + "m/TestCase\"`\n\031BatchRunTestCasesResponse\022"
          + "C\n\007results\030\001 \003(\01322.google.cloud.dialogfl"
          + "ow.cx.v3beta1.TestCaseResult\"Z\n\031BatchRun"
          + "TestCasesMetadata\022=\n\006errors\030\001 \003(\0132-.goog"
          + "le.cloud.dialogflow.cx.v3beta1.TestError"
          + "\"\232\001\n\tTestError\022:\n\ttest_case\030\001 \001(\tB\'\372A$\n\""
          + "dialogflow.googleapis.com/TestCase\022\"\n\006st"
          + "atus\030\002 \001(\0132\022.google.rpc.Status\022-\n\ttest_t"
          + "ime\030\003 \001(\0132\032.google.protobuf.Timestamp\"\204\001"
          + "\n\026ImportTestCasesRequest\022:\n\006parent\030\001 \001(\t"
          + "B*\340A\002\372A$\022\"dialogflow.googleapis.com/Test"
          + "Case\022\021\n\007gcs_uri\030\002 \001(\tH\000\022\021\n\007content\030\003 \001(\014"
          + "H\000B\010\n\006source\"Q\n\027ImportTestCasesResponse\022"
          + "6\n\005names\030\001 \003(\tB\'\372A$\n\"dialogflow.googleap"
          + "is.com/TestCase\"\\\n\027ImportTestCasesMetada"
          + "ta\022A\n\006errors\030\001 \003(\01321.google.cloud.dialog"
          + "flow.cx.v3beta1.TestCaseError\"t\n\rTestCas"
          + "eError\022?\n\ttest_case\030\001 \001(\0132,.google.cloud"
          + ".dialogflow.cx.v3beta1.TestCase\022\"\n\006statu"
          + "s\030\002 \001(\0132\022.google.rpc.Status\"\241\002\n\026ExportTe"
          + "stCasesRequest\022:\n\006parent\030\001 \001(\tB*\340A\002\372A$\022\""
          + "dialogflow.googleapis.com/TestCase\022\021\n\007gc"
          + "s_uri\030\002 \001(\tH\000\022Z\n\013data_format\030\003 \001(\0162E.goo"
          + "gle.cloud.dialogflow.cx.v3beta1.ExportTe"
          + "stCasesRequest.DataFormat\022\016\n\006filter\030\004 \001("
          + "\t\"=\n\nDataFormat\022\033\n\027DATA_FORMAT_UNSPECIFI"
          + "ED\020\000\022\010\n\004BLOB\020\001\022\010\n\004JSON\020\002B\r\n\013destination\""
          + "N\n\027ExportTestCasesResponse\022\021\n\007gcs_uri\030\001 "
          + "\001(\tH\000\022\021\n\007content\030\002 \001(\014H\000B\r\n\013destination\""
          + "\031\n\027ExportTestCasesMetadata\"\225\001\n\032ListTestC"
          + "aseResultsRequest\022@\n\006parent\030\001 \001(\tB0\340A\002\372A"
          + "*\022(dialogflow.googleapis.com/TestCaseRes"
          + "ult\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001"
          + "(\t\022\016\n\006filter\030\004 \001(\t\"\205\001\n\033ListTestCaseResul"
          + "tsResponse\022M\n\021test_case_results\030\001 \003(\01322."
          + "google.cloud.dialogflow.cx.v3beta1.TestC"
          + "aseResult\022\027\n\017next_page_token\030\002 \001(\t*A\n\nTe"
          + "stResult\022\033\n\027TEST_RESULT_UNSPECIFIED\020\000\022\n\n"
          + "\006PASSED\020\001\022\n\n\006FAILED\020\0022\317\024\n\tTestCases\022\322\001\n\r"
          + "ListTestCases\0228.google.cloud.dialogflow."
          + "cx.v3beta1.ListTestCasesRequest\0329.google"
          + ".cloud.dialogflow.cx.v3beta1.ListTestCas"
          + "esResponse\"L\202\323\344\223\002=\022;/v3beta1/{parent=pro"
          + "jects/*/locations/*/agents/*}/testCases\332"
          + "A\006parent\022\314\001\n\024BatchDeleteTestCases\022?.goog"
          + "le.cloud.dialogflow.cx.v3beta1.BatchDele"
          + "teTestCasesRequest\032\026.google.protobuf.Emp"
          + "ty\"[\202\323\344\223\002L\"G/v3beta1/{parent=projects/*/"
          + "locations/*/agents/*}/testCases:batchDel"
          + "ete:\001*\332A\006parent\022\277\001\n\013GetTestCase\0226.google"
          + ".cloud.dialogflow.cx.v3beta1.GetTestCase"
          + "Request\032,.google.cloud.dialogflow.cx.v3b"
          + "eta1.TestCase\"J\202\323\344\223\002=\022;/v3beta1/{name=pr"
          + "ojects/*/locations/*/agents/*/testCases/"
          + "*}\332A\004name\022\334\001\n\016CreateTestCase\0229.google.cl"
          + "oud.dialogflow.cx.v3beta1.CreateTestCase"
          + "Request\032,.google.cloud.dialogflow.cx.v3b"
          + "eta1.TestCase\"a\202\323\344\223\002H\";/v3beta1/{parent="
          + "projects/*/locations/*/agents/*}/testCas"
          + "es:\ttest_case\332A\020parent,test_case\022\353\001\n\016Upd"
          + "ateTestCase\0229.google.cloud.dialogflow.cx"
          + ".v3beta1.UpdateTestCaseRequest\032,.google."
          + "cloud.dialogflow.cx.v3beta1.TestCase\"p\202\323"
          + "\344\223\002R2E/v3beta1/{test_case.name=projects/"
          + "*/locations/*/agents/*/testCases/*}:\ttes"
          + "t_case\332A\025test_case,update_mask\022\324\001\n\013RunTe"
          + "stCase\0226.google.cloud.dialogflow.cx.v3be"
          + "ta1.RunTestCaseRequest\032\035.google.longrunn"
          + "ing.Operation\"n\202\323\344\223\002;\"6/v3beta1/projects"
          + "/*/locations/*/agents/*/testCases:run:\001*"
          + "\312A*\n\023RunTestCaseResponse\022\023RunTestCaseMet"
          + "adata\022\373\001\n\021BatchRunTestCases\022<.google.clo"
          + "ud.dialogflow.cx.v3beta1.BatchRunTestCas"
          + "esRequest\032\035.google.longrunning.Operation"
          + "\"\210\001\202\323\344\223\002I\"D/v3beta1/{parent=projects/*/l"
          + "ocations/*/agents/*}/testCases:batchRun:"
          + "\001*\312A6\n\031BatchRunTestCasesResponse\022\031BatchR"
          + "unTestCasesMetadata\022\346\001\n\021CalculateCoverag"
          + "e\022<.google.cloud.dialogflow.cx.v3beta1.C"
          + "alculateCoverageRequest\032=.google.cloud.d"
          + "ialogflow.cx.v3beta1.CalculateCoverageRe"
          + "sponse\"T\202\323\344\223\002N\022L/v3beta1/{agent=projects"
          + "/*/locations/*/agents/*}/testCases:calcu"
          + "lateCoverage\022\361\001\n\017ImportTestCases\022:.googl"
          + "e.cloud.dialogflow.cx.v3beta1.ImportTest"
          + "CasesRequest\032\035.google.longrunning.Operat"
          + "ion\"\202\001\202\323\344\223\002G\"B/v3beta1/{parent=projects/"
          + "*/locations/*/agents/*}/testCases:import"
          + ":\001*\312A2\n\027ImportTestCasesResponse\022\027ImportT"
          + "estCasesMetadata\022\361\001\n\017ExportTestCases\022:.g"
          + "oogle.cloud.dialogflow.cx.v3beta1.Export"
          + "TestCasesRequest\032\035.google.longrunning.Op"
          + "eration\"\202\001\202\323\344\223\002G\"B/v3beta1/{parent=proje"
          + "cts/*/locations/*/agents/*}/testCases:ex"
          + "port:\001*\312A2\n\027ExportTestCasesResponse\022\027Exp"
          + "ortTestCasesMetadata\022\356\001\n\023ListTestCaseRes"
          + "ults\022>.google.cloud.dialogflow.cx.v3beta"
          + "1.ListTestCaseResultsRequest\032?.google.cl"
          + "oud.dialogflow.cx.v3beta1.ListTestCaseRe"
          + "sultsResponse\"V\202\323\344\223\002G\022E/v3beta1/{parent="
          + "projects/*/locations/*/agents/*/testCase"
          + "s/*}/results\332A\006parent\032x\312A\031dialogflow.goo"
          + "gleapis.com\322AYhttps://www.googleapis.com"
          + "/auth/cloud-platform,https://www.googlea"
          + "pis.com/auth/dialogflowB\254\001\n&com.google.c"
          + "loud.dialogflow.cx.v3beta1B\rTestCaseProt"
          + "oP\001ZDgoogle.golang.org/genproto/googleap"
          + "is/cloud/dialogflow/cx/v3beta1;cx\370\001\001\242\002\002D"
          + "F\252\002\"Google.Cloud.Dialogflow.Cx.V3Beta1b\006"
          + "proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.dialogflow.cx.v3beta1.FlowProto.getDescriptor(),
              com.google.cloud.dialogflow.cx.v3beta1.IntentProto.getDescriptor(),
              com.google.cloud.dialogflow.cx.v3beta1.PageProto.getDescriptor(),
              com.google.cloud.dialogflow.cx.v3beta1.ResponseMessageProto.getDescriptor(),
              com.google.cloud.dialogflow.cx.v3beta1.SessionProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCase_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCase_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestCase_descriptor,
            new java.lang.String[] {
              "Name",
              "Tags",
              "DisplayName",
              "Notes",
              "TestConfig",
              "TestCaseConversationTurns",
              "CreationTime",
              "LastTestResult",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseResult_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseResult_descriptor,
            new java.lang.String[] {
              "Name", "Environment", "ConversationTurns", "TestResult", "TestTime",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestConfig_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestConfig_descriptor,
            new java.lang.String[] {
              "TrackingParameters", "Flow",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_descriptor,
            new java.lang.String[] {
              "UserInput", "VirtualAgentOutput",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_UserInput_descriptor =
        internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_UserInput_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_UserInput_descriptor,
            new java.lang.String[] {
              "Input", "InjectedParameters", "IsWebhookEnabled",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_VirtualAgentOutput_descriptor =
        internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_VirtualAgentOutput_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ConversationTurn_VirtualAgentOutput_descriptor,
            new java.lang.String[] {
              "SessionParameters",
              "Differences",
              "DiagnosticInfo",
              "TriggeredIntent",
              "CurrentPage",
              "TextResponses",
              "Status",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestRunDifference_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestRunDifference_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestRunDifference_descriptor,
            new java.lang.String[] {
              "Type", "Description",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_descriptor,
            new java.lang.String[] {
              "Transitions", "CoverageScore",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_TransitionNode_descriptor =
        internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_TransitionNode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_TransitionNode_descriptor,
            new java.lang.String[] {
              "Page", "Flow", "Kind",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_Transition_descriptor =
        internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_Transition_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TransitionCoverage_Transition_descriptor,
            new java.lang.String[] {
              "Source", "Index", "Target", "Covered", "TransitionRoute", "EventHandler", "Detail",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_descriptor,
            new java.lang.String[] {
              "Intents", "CoverageScore",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_Intent_descriptor =
        internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_Intent_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_IntentCoverage_Intent_descriptor,
            new java.lang.String[] {
              "Intent", "Covered",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageRequest_descriptor,
            new java.lang.String[] {
              "Agent", "Type",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageResponse_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_CalculateCoverageResponse_descriptor,
            new java.lang.String[] {
              "Agent", "IntentCoverage", "TransitionCoverage", "CoverageType",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "View",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesResponse_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCasesResponse_descriptor,
            new java.lang.String[] {
              "TestCases", "NextPageToken",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchDeleteTestCasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchDeleteTestCasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_BatchDeleteTestCasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Names",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_CreateTestCaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_dialogflow_cx_v3beta1_CreateTestCaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_CreateTestCaseRequest_descriptor,
            new java.lang.String[] {
              "Parent", "TestCase",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_UpdateTestCaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_dialogflow_cx_v3beta1_UpdateTestCaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_UpdateTestCaseRequest_descriptor,
            new java.lang.String[] {
              "TestCase", "UpdateMask",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_GetTestCaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_dialogflow_cx_v3beta1_GetTestCaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_GetTestCaseRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseRequest_descriptor,
            new java.lang.String[] {
              "Name", "Environment",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseResponse_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseResponse_descriptor,
            new java.lang.String[] {
              "Result",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseMetadata_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_RunTestCaseMetadata_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Environment", "TestCases",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesResponse_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesResponse_descriptor,
            new java.lang.String[] {
              "Results",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesMetadata_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_BatchRunTestCasesMetadata_descriptor,
            new java.lang.String[] {
              "Errors",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestError_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestError_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestError_descriptor,
            new java.lang.String[] {
              "TestCase", "Status", "TestTime",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "GcsUri", "Content", "Source",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesResponse_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesResponse_descriptor,
            new java.lang.String[] {
              "Names",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesMetadata_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ImportTestCasesMetadata_descriptor,
            new java.lang.String[] {
              "Errors",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseError_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseError_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_TestCaseError_descriptor,
            new java.lang.String[] {
              "TestCase", "Status",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "GcsUri", "DataFormat", "Filter", "Destination",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesResponse_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesResponse_descriptor,
            new java.lang.String[] {
              "GcsUri", "Content", "Destination",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesMetadata_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ExportTestCasesMetadata_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsRequest_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter",
            });
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsResponse_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_dialogflow_cx_v3beta1_ListTestCaseResultsResponse_descriptor,
            new java.lang.String[] {
              "TestCaseResults", "NextPageToken",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.dialogflow.cx.v3beta1.FlowProto.getDescriptor();
    com.google.cloud.dialogflow.cx.v3beta1.IntentProto.getDescriptor();
    com.google.cloud.dialogflow.cx.v3beta1.PageProto.getDescriptor();
    com.google.cloud.dialogflow.cx.v3beta1.ResponseMessageProto.getDescriptor();
    com.google.cloud.dialogflow.cx.v3beta1.SessionProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
